---
abstract: 'rafl is so everywhere, he has his own Acme module!'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-rafl-Everywhere
no_index:
  file:
    - README.pod
requires:
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/xsawyerx/acme-rafl-everywhere/issues
  repository: http://github.com/xsawyerx/acme-rafl-everywhere
version: 0.006
